### ISSUE TITLE
iOS error

### ISSUE THREAD

**Issue by cbfischer** [karantanwar/unique_identifier#1]
Hi, 

I'm trying to use the plugin and the following error is occurring:

- `unique_identifier` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

 ```
   /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'
```

**Comment by karantanwar** [comment]
Thanks for raising the issue... i'll fix it right away.... and sorry for the late reply.... i thought no-one was using this plugin except me

**Comment by tkleijkers** [comment]
Is it already fixed?

**Comment by kraxarn** [comment]
As this is not fixed yet, I decided to change to using the `device_id` library which does about the same, but it works.

**Comment by kraxarn** [comment]
Adding `ENV['SWIFT_VERSION'] = '5.0'` to the podilfe solves that error, but now instead it complains about the missing life `unique_identifier-Swift-h`.
Following the instructions from [here](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492) does work (using Swift 5.0 instead of 3.2), but this plugin really needs to be rewritten in Objective-C.

**Comment by joknjokn** [comment]
No news about this bug?

**Comment by vhbmsp** [comment]
@karantanwar FYI: It is still broken.

**Comment by paulobreim** [comment]
This problem start when Apple release the last xcode.


[!] Unable to determine Swift version for the following pods:

- `unique_identifier` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by bytelyus** [comment]
fixed mine by manually editing _'anyway'_  **'unique_identifier.podspec'** file under 'Flutter Plugins' folder > unique_identifier folder > ios folder ...

Just added this line before 'end' of file

s.swift_version = '4.0'

...

Update pluging, please.. many people (2 at least) over here using it!! ...

Note that phones with dual sim may change the unique_identifier when using one sim or another!

<3 Flutter!
