### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by danieldoddjr** [karantanwar/unique_identifier#12]
Today after updating to Flutter 2.5 and Upgrading Android Studio I get this warning when I flutter run.

The plugin `unique_identifier` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the
Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these
deprecated APIs.

If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by paulobreim** [comment]
Same for me

**Comment by paulobreim** [comment]
good news,
Mr. Karan sent me a message that he will work on it.

**Comment by karantanwar** [comment]
Hi... I am sorry for the delay... I am a little busy with a different project... I'll resolve this soon.

**Comment by paulobreim** [comment]
i saw that there is a new version, i haven't tested it yet but it probably fixed the problem. 
unique_identifier: ^0.2.2

**Comment by paulobreim** [comment]
@karantanwar 
Still
The plugin `unique_identifier` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the
Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove
these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

Please fix it or tell to us if you will not support any more
